# to run in local, just execute this file :)
version: "3.9"
services:
  backend:
    build: ./backend/geo-service/
    ports:
      - "3001:3001"
  frontend:
    build: ./frontend/delivery/
    environment:
      - GEO_SERVICE_HOST="localhost:3001"
    ports:
      - "8080:80"
